### PR TITLE
update queries with sql in materialized view

### PR DESCRIPTION
**Pull request by cdolfi**
This adds the sql query for materialized view in comments

### CODE REVIEW

**Comment by cdolfi** [comment]
@JamesKunstle Im not too familiar with how materialized views work on if there is a way to "read" a materialized view. Ill noodle on where we can put the current sql write out and talk to sean about the possibility of "reading" the materialized view once we get past this current set of augur fixes

**Comment by cdolfi** [comment]
@sgoggins just to confirm, materialized views are unique to a single db?

**Comment by JamesKunstle** [comment]
@cdolfi I'd write the query as a .sql document in the 8Knot/docs folder and put a reference to that file in the company and contributors function docstrings.

**Comment by cdolfi** [comment]
@JamesKunstle great ideas, implemented it. This is ready for review again

**Review by JamesKunstle — APPROVED** [review]
Ideal, lgtm!

**Pull request merged**
