### PR TITLE
PR and issue assignment optimization 

### PR DESCRIPTION
**Pull request by cdolfi**
Might need more updates to optimize more but this makes a HUGE difference

### CODE REVIEW

**Comment by JamesKunstle** [comment]
@cdolfi This limits the range of dates for which the graph is rendered, correct? So, we're visualizing the data the same way, but we're visualizing less data at once by default with this change.

**Comment by cdolfi** [comment]
@JamesKunstle Yes precisely, the initial rendering takes so much less time than before

**Comment by JamesKunstle** [comment]
@cdolfi In testing, this is much better than before. I think we still ought to aggregate small values of assignments, and let the user know that un-aggregating will have a browser performance penalty. For the Kubernetes org, I get the following:

Screenshot 2024-01-08 at 4 27 06 PM

Which is very slow to interact with.

**Comment by cdolfi** [comment]
@JamesKunstle That makes sense to me, can you detail what you have in mind in the issue linked? Think itd be good to do in a separate PR (and would not close said issue w this PR)

**Comment by JamesKunstle** [comment]
Yeah I definitely can

**Comment by JamesKunstle** [comment]
#613 opened this issue, and #614 this one

**Review by JamesKunstle — APPROVED** [review]

**Comment by JamesKunstle** [comment]
you'll have to rebase the branch manually for it to be merged.

**Pull request merged**
