### PR TITLE
set the searchbar default from the environment

### PR DESCRIPTION
**Pull request by JamesKunstle**
allows deployer to set an environment variable for the label of the repo/org they'd like the searchbar to default to on startup.

If the variable not set, default is the first option available in the options list.

### CODE REVIEW

**Review by cdolfi — CHANGES_REQUESTED** [review]
Drop the pie chart changes and then lgtm. Let me know what I need to add to my local variables

**Comment by JamesKunstle** [comment]
@cdolfi the changes to the piechart file are from pre-commit, I'd prefer to just accept them here rather than creating a new PR for them.

**Comment by cdolfi** [comment]
@JamesKunstle that makes 100% sense merging now

**Review by cdolfi — APPROVED** [review]
lgtm with context of pie updates

**Pull request merged**
