### PR TITLE
fix issue_assignee_query and pr_assignee_query

### PR DESCRIPTION
**Pull request by JamesKunstle**

### CODE REVIEW

**Comment by cdolfi** [comment]
@JamesKunstle is this still relevent / necessary?

**Review by cdolfi — APPROVED** [review]
still a little confused as to why this doesnt work on your branch in current state as it does on mine (even after rebuild) but they are equivalent so lgtm

**Comment by JamesKunstle** [comment]
> https://github.com/oss-aspen/8Knot/issues/487 confused bc of the closing and comment of this

#487 addresses the problem but misidentifies the cause as being from the materialized view. 

This PR just fixes up the application query to be correct SQL, keeping the materialized view as-is.

**Comment by JamesKunstle** [comment]
> still a little confused as to why this doesnt work on your branch in current state as it does on mine (even after rebuild) but they are equivalent so lgtm

Did you delete the existing Redis container?

`docker compose down; docker compose up --build`

The query wasn't fully correct SQL so it shouldn't work anywhere- it doesn't work in dbeaver. I'm guessing the cache container was still warm despite rebuild, which would happen if you didn't `down` the compose.

**Comment by cdolfi** [comment]
sounds good im good to merge

**Pull request merged**
