### PR TITLE
Contributor pull request review assignment

### PR DESCRIPTION
**Pull request by cdolfi**
Things to note during review: 

- We should consider before turning this query into a materialized view if we want to join on the contributors table to have the login info available off the bat for viewing on a local/private instance 
- the conversation on pages will definitely move the location of the graph. This location is temporary until we have a good home for it. I have a few visualizations that are close to done and once those are in lets discuss new page break downs   
- Ctrb_id on the hover is on the side. Currently thats the only way I can see how to do it with the cntb_id not being static (spent multiple hours yesterday trying to figure it out)

### CODE REVIEW

**Comment by JamesKunstle** [comment]
@cdolfi My comments on #442 apply here nearly directly- same rationale, pretty willing to just merge this after we've solidified the Info section and the interface.

**Review by JamesKunstle — CHANGES_REQUESTED** [review]
in other comment

**Comment by JamesKunstle** [comment]
@cdolfi same comments now as for #442

**Comment by cdolfi** [comment]
@JamesKunstle ready for review based on comments

**Comment by JamesKunstle** [comment]
@cdolfi responded to both in #442, very nearly at consensus

**Review by JamesKunstle — APPROVED** [review]
lgtm w/ new understanding

**Pull request merged**
