### PR TITLE
Ocp patch

### PR DESCRIPTION
**Pull request by JamesKunstle**
Changes default pod scaling on cluster

### CODE REVIEW

**Review by cdolfi — CHANGES_REQUESTED** [review]
lgtm, once this is brought up to date w dev and commits squashed ill merge

**Comment by JamesKunstle** [comment]
@cdolfi made changes

**Comment by cdolfi** [comment]
@JamesKunstle still showing out of date on my side

**Comment by JamesKunstle** [comment]
@cdolfi should be updated

**Review by cdolfi — APPROVED** [review]
lgtm

**Pull request merged**
